stages:
  preprocess:
    cmd: poetry run preprocess-images -d data/raw -o data/prepared
    deps:
    - data/raw
    - intel_image_classification/preprocess_dataset.py
    outs:
    - data/prepared/train
    - data/prepared/test
  train:
    cmd: poetry run train --dataset-path data/prepared/train -o model.pkl
    deps:
    - data/prepared/train/
    - intel_image_classification/train.py
    params:
    - train
    outs:
    - model.pkl
    - dvclive
  evaluate:
    cmd: poetry run evaluate --model-path model.pkl
    deps:
    - data/prepared/test
    - intel_image_classification/evaluate.py
    - model.pkl
    - dvclive
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
